import { IMapDescript } from "../types/mapSvgType";

export default [
  {
    map: "tablo",
    url: "./svg/tablo.svg",
    img_leg: "./svg/legend.svg",
    img_spec: null,
    keys: ["main"],
    uid: 0,
  },
  {
    map: "big_tablo",
    url: "./svg/big_tablo.svg",
    img_leg: "./svg/big_legend.svg",
    img_spec: null,
    keys: ["big_main"],
    uid: 10,
  },
  {
    map: "nod1",
    url: "./svg/moscow.svg",
    img_leg: "./svg/moscow_legend.svg",
    img_spec: "./svg/moscow_legend_table.svg",
    keys: ["nod1", "go_moscow"],
    uid: 1,
  },
  {
    map: "nod2",
    url: "./svg/vit.svg",
    img_leg: "./svg/vit_legend.svg",
    img_spec: "./svg/vit_legend_table.svg",
    keys: ["nod2", "go_spb_vit"],
    uid: 2,
  },
  {
    map: "nod3",
    url: "./svg/spb.svg",
    img_leg: "./svg/spb_legend.svg",
    img_spec: "./svg/spb_legend_table.svg",
    keys: ["nod3", "go_spb"],
    uid: 3,
  },
  {
    map: "nod4",
    url: "./svg/petrozavodsk.svg",
    img_leg: "./svg/petrozavodsk_legend.svg",
    img_spec: "./svg/petrozavodsk_legend_table.svg",
    keys: ["nod4", "go_petrozavodsk"],
    uid: 4,
  },
  {
    map: "nod5",
    url: "./svg/murm.svg",
    img_leg: "./svg/murm_legend.svg",
    img_spec: "./svg/murm_legend_table.svg",
    keys: ["nod5", "go_murm"],
    uid: 5,
  },
  {
    map: "nod6",
    url: "./svg/volhov.svg",
    img_leg: "./svg/volhov_legend.svg",
    img_spec: "./svg/volhov_legend_table.svg",
    keys: ["nod6", "go_volhov"],
    uid: 6,
  },
  {
    map: "city",
    url: "./svg/city.svg",
    img_leg: "./svg/city_legend.svg",
    keys: ["city", "go_city"],
    uid: 7,
  },
] as IMapDescript[];
