// Конфигуратор слоев
//
/**************
   "Подразделения": 1,
   "Локомотивный комплекс": 2,
   "Тепло/водоснабжение": 3,
   "Связь": 4,
   "Погодные условия": 5,
   "Искусственные сооружения": 6,
   "Здоровый образ жизни": 7,
 *****************/

import { LayerDescript } from "../types/layerType";

export const layersInit: LayerDescript[] = [
  {
    layer: "pch",
    check: false,
    name: "Границы ПЧ",
    visible: "visible",
    disabled: false,
    id: 0,
    group: 1,
  },
  {
    layer: "shch",
    check: false,
    name: "Границы ШЧ",
    visible: "visible",
    disabled: false,
    id: 1,
    group: 1,
  },
  {
    layer: "vchd",
    check: false,
    name: "Границы ВЧД",
    visible: "visible",
    disabled: false,
    id: 2,
    group: 1,
  },
  {
    layer: "ech",
    check: false,
    name: "Границы ЭЧ",
    visible: "visible",
    disabled: false,
    id: 3,
    group: 1,
  },
  {
    layer: "dnc",
    check: false,
    name: "Диспетчерские участки",
    visible: "visible",
    disabled: false,
    id: 4,
    group: 1,
  },
  {
    layer: "ngch",
    check: false,
    name: "НГЧ, дистанция гражданских сооружений",
    visible: "visible",
    disabled: false,
    id: 5,
    group: 1,
  },
  {
    layer: "current",
    check: false,
    name: "Электрификация",
    visible: "visible",
    disabled: false,
    id: 6,
    group: 1,
  },
  {
    layer: "loco fuel_base",
    check: false,
    name: "Схема тягового обслуживания локомотивами (грузовые поезда)",
    visible: "visible",
    disabled: false,
    id: 7,
    group: 2,
  },
  {
    layer: "loco_team dolb",
    check: false,
    name:
      "Схема тягового обслуживания локомотивными бригадами (грузовые поезда)",
    visible: "visible",
    disabled: false,
    id: 8,
    group: 2,
  },
  {
    layer: "loco_pass fuel_base_pass",
    check: false,
    name: "Схема тягового обслуживания локомотивами (пассажирские поезда)",
    visible: "visible",
    disabled: false,
    id: 9,
    group: 2,
  },
  {
    layer: "loco_team_pass",
    check: false,
    name:
      "Схема тягового обслуживания локомотивными бригадами (пассажирские поезда)",
    visible: "visible",
    disabled: false,
    id: 10,
    group: 2,
  },
  {
    layer: "spec_trains",
    check: false,
    name: "Восстановительные, пожарные и противоразмывные поезда",
    visible: "visible",
    disabled: false,
    id: 11,
    group: 2,
  },
  {
    layer: "ftrains_area",
    check: false,
    name: "Зоны обслуживания пожарными поездами",
    visible: "visible",
    disabled: false,
    id: 12,
    group: 2,
  },
  {
    layer: "dtv",
    check: false,
    name: "ДТВУ",
    visible: "visible",
    disabled: false,
    id: 13,
    group: 3,
  },
  {
    layer: "rcs",
    check: false,
    name: "Границы РЦС, поездная радиосвязь",
    visible: "visible",
    disabled: false,
    id: 14,
    group: 4,
  },

  {
    layer: "mls",
    check: false,
    name: "Границы РЦС, линии связи",
    visible: "visible",
    disabled: false,
    id: 15,
    group: 4,
  },
  {
    layer: "trains_distantions",
    check: true,
    name: "Штормовое предупреждение",
    visible: "visible",
    disabled: false,
    id: 16,
    group: 5,
  },

  {
    layer: "snow_tech",
    check: false,
    name: "Снегоуборочная техника",
    visible: "visible",
    disabled: false,
    id: 17,
    group: 5,
  },
  {
    layer: "weather_st",
    check: false,
    name: "Фактическая погода",
    visible: "visible",
    disabled: false,
    id: 18,
    group: 5,
  },
  {
    layer: "bridges",
    check: false,
    name: "мосты",
    visible: "visible",
    disabled: false,
    id: 19,
    group: 6,
  },
  {
    layer: "tubes",
    check: false,
    name: "трубы ИССО",
    visible: "visible",
    disabled: false,
    id: 20,
    group: 6,
  },
  {
    layer: "health_org",
    check: false,
    name: "Физкультурно-спортивные клубы",
    visible: "visible",
    disabled: false,
    id: 21,
    group: 7,
  },
];
